# Project: Project2
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = B-Tree.o main.o
LINKOBJ  = B-Tree.o main.o
LIBS     = -L"D:/Document/EMBARCODE/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib32" -static-libgcc -m32 -pg -g3
INCS     = -I"D:/Document/EMBARCODE/Dev-Cpp/TDM-GCC-64/include" -I"D:/Document/EMBARCODE/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Document/EMBARCODE/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/Document/EMBARCODE/Dev-Cpp/TDM-GCC-64/include" -I"D:/Document/EMBARCODE/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Document/EMBARCODE/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/Document/EMBARCODE/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = BinaryTree.exe
CXXFLAGS = $(CXXINCS) -m32 -pg -g3
CFLAGS   = $(INCS) -m32 -pg -g3
DEL      = D:\Document\EMBARCODE\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

B-Tree.o: B-Tree.cpp
	$(CPP) -c B-Tree.cpp -o B-Tree.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
